# Generated by Django 2.1.3 on 2018-11-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='namr',
            new_name='name',
        ),
    ]
